# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='demo',
  syntax='proto3',
  serialized_options=b'\n\032io.grpc.examples.demoprotoB\tDemoProtoP\001\242\002\003RTG',
  serialized_pb=b'\n\ndemo.proto\x12\x04\x64\x65mo\"\x18\n\x08Userinfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x08Greeting\x12\x10\n\x08greeting\x18\x01 \x01(\t24\n\x04\x44\x65mo\x12,\n\x08SayHello\x12\x0e.demo.Userinfo\x1a\x0e.demo.Greeting\"\x00\x42/\n\x1aio.grpc.examples.demoprotoB\tDemoProtoP\x01\xa2\x02\x03RTGb\x06proto3'
)




_USERINFO = _descriptor.Descriptor(
  name='Userinfo',
  full_name='demo.Userinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='demo.Userinfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)


_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='demo.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='demo.Greeting.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['Userinfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Userinfo = _reflection.GeneratedProtocolMessageType('Userinfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Userinfo)
  })
_sym_db.RegisterMessage(Userinfo)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Greeting)
  })
_sym_db.RegisterMessage(Greeting)


DESCRIPTOR._options = None

_DEMO = _descriptor.ServiceDescriptor(
  name='Demo',
  full_name='demo.Demo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=76,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='demo.Demo.SayHello',
    index=0,
    containing_service=None,
    input_type=_USERINFO,
    output_type=_GREETING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMO)

DESCRIPTOR.services_by_name['Demo'] = _DEMO

# @@protoc_insertion_point(module_scope)
